zuul:
  prefix: /api/v1
  routes:
    student-service:
      path: /student-svr/**
      service-id: STUDENT-SERVICE
    schedule-service:
      path: /schedule-svr/**
      service-id: SCHEDULE-SERVICE
    course-service:
      path: /course-svr/**
      service-id: COURSE-SERVICE
    score-service:
      path: /score-svr/**
      service-id: SCORE-SERVICE
  host:
    connect-timeout-millis: 100000000 
    socket-timeout-millis: 100000000 

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

server:
  port: 8090

spring:
  application:
    name: sn-gateway-service
